[tools]
chezmoi = "latest"
neovim = "latest"
rg = "latest"
rust = "latest"
zoxide = "latest"
go = "latest"
node = "latest"
fzf = "latest"
kubectl = "latest"
python = "latest"
k9s = "latest"
fx = "latest"
yq = "latest"
jq = "latest"
age = "latest"
